### 方法1：标准化缩放法
- 对简单示例二维矩阵的列数据进行

In [2]:
from sklearn import preprocessing
import numpy as np

#### 方法1: 标准化缩放法 对简单实例二维矩阵的列数据进行

In [18]:
X = np.array([[0,0],# 采用numpy的array表示，因为要用到其mean等函数，而list没有这些函数
            [0,0],
            [100,1],
            [1,1]])
X_mean = X.mean(axis = 0)
X_std = X.std(axis = 0)
# print(X_std)
# print(X_mean)
X1 = (X-X_mean)/X_std
print(X1)
# 利用一个集成的方法
# X2 = preprocessing.scale(X)
# print(X2)

[[-0.58504784 -1.        ]
 [-0.58504784 -1.        ]
 [ 1.73197332  1.        ]
 [-0.56187763  1.        ]]


#### 方法1： 标准化缩放法 对 iris数据二维矩阵的列数据进行

In [20]:
from sklearn import datasets
iris = datasets.load_iris()
X_scale = preprocessing.scale(iris.data)
print(X_scale)

[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+00 -1.45390138e+00 -1.31544430e

#### 方法2: 区间缩放法 对简单示例二维矩阵的列数据进行

In [24]:
from sklearn.preprocessing import MinMaxScaler
data = [[0,0],
       [0,0],
       [100,1],
       [1,1]]
scaler = MinMaxScaler()
print(scaler.fit(data))
print(scaler.transform(data)) #用此方法，必须使用fit先进行预处理计算均值和标准差

MinMaxScaler(copy=True, feature_range=(0, 1))
[[0.   0.  ]
 [0.   0.  ]
 [1.   1.  ]
 [0.01 1.  ]]


#### 方法2： 区间缩放法 对iris数据二维矩阵的列数据

In [29]:
from sklearn.preprocessing import MinMaxScaler
data = iris.data
scaler = MinMaxScaler()
print(scaler.fit(data))
print(scaler.transform(data))

MinMaxScaler(copy=True, feature_range=(0, 1))
[[0.22222222 0.625      0.06779661 0.04166667]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]
 [0.30555556 0.79166667 0.11864407 0.125     ]
 [0.08333333 0.58333333 0.06779661 0.08333333]
 [0.19444444 0.58333333 0.08474576 0.04166667]
 [0.02777778 0.375      0.06779661 0.04166667]
 [0.16666667 0.45833333 0.08474576 0.        ]
 [0.30555556 0.70833333 0.08474576 0.04166667]
 [0.13888889 0.58333333 0.10169492 0.04166667]
 [0.13888889 0.41666667 0.06779661 0.        ]
 [0.         0.41666667 0.01694915 0.        ]
 [0.41666667 0.83333333 0.03389831 0.04166667]
 [0.38888889 1.         0.08474576 0.125     ]
 [0.30555556 0.79166667 0.05084746 0.125     ]
 [0.22222222 0.625      0.06779661 0.08333333]
 [0.38888889 0.75       0.11864407 0.08333333]
 [0.22222222 0.75       0.08474576 0.08333333]
 [0.30555556 0

In [31]:
import numpy as np
from scipy.stats import pearsonr
x = np.random.uniform(-1,1,100000)
print(pearsonr(x,x*2)[0])
print(pearsonr(x,x**2)[0])

1.0
0.004375897406904467
