In [6]:
import tensorflow as tf
print(tf.__version__)                                   #tensorflow 的版本
node1 = tf.constant([[3.0,1.5],[2.5,6.0]],tf.float32)   #创建两个常量
node2 = tf.constant([[4.0,1.0],[5.0,2.5]],tf.float32)
node3 = tf.add(node1,node2)  # 定义加法运算

node3

2.1.0


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[7. , 2.5],
       [7.5, 8.5]], dtype=float32)>

##### 输出的是一个Tensor

In [4]:
print(node3.numpy())

[[7.  2.5]
 [7.5 8.5]]


In [16]:
scalar = tf.constant(100)
vector = tf.constant([1,2,3,4,5])
matrix = tf.constant([[1,2,3],[4,5,6]])
cube_matrix = tf.constant([[[1],[2],[3]],[[4],[5],[6]],[[7],[8],[9]]])

print(scalar.shape)
print(vector.shape)
print(matrix.shape)
print(cube_matrix.get_shape())

()
(5,)
(2, 3)
(3, 3, 1)


In [17]:
cube_matrix = tf.constant([[[1],[2],[3]],[[4],[5],[6]],[[7],[8],[9]]])
print(cube_matrix.numpy()[1,2,0])

6


#####  每个张量都会有一个唯一的类型，Tensorflow在进行运算的时候会对参与运算的所有张量进行类型的检查

In [18]:
a = tf.constant([1,2])
b = tf.constant([2.0,3.0])

result = tf.add(a,b)        #运行报错

InvalidArgumentError: cannot compute Add as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:Add]

##### 在Tensorflow中可以通过tf.cast()进行数据类型转换

In [29]:
a = tf.constant([1,2])
b = tf.constant([2.0,3.0])

a = tf.cast(a,tf.float32)   #数据类型转换

result = tf.add(a,b)
result

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 5.], dtype=float32)>

##### 在创建常量时只有value值是必填的，dtype等参数可以缺省，会根据具体的value值设置相应的值

In [22]:
a = tf.constant([1,2])
a

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

###### 在创建的同时指定数据类型，在数据兼容的情况下会自动做数据类型转换

In [23]:
b = tf.constant([3,4],tf.float32)
b

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 4.], dtype=float32)>

###### 如果shape参数值被设定，则会做相应的reshape工作

In [24]:
c = tf.constant([1,2,3,4,5,6],shape=[2,3])
c

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

##### 变量在创建时必须确定初始值，可以像定义常量一样

In [25]:
v1 = tf.Variable([1,2])
v2 = tf.Variable([3,4],tf.float32)
v1,v2

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2])>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 4])>)

##### 也可以用一个张量作为初始值

In [28]:
c = tf.constant(1)
v = tf.Variable(c)

c,v

(<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>)

##### 在Tensorflow中变量创建后，一般无需人工进行赋值，系统会根据算法模型，在训练优化过程中自动调整变量的值

##### 在变量的参数中，trainable参数用来表征当前变量是否需要被自动优化，默认是启动自动优化标志

#### 特殊情况需要人工更新的，可用变量赋值语句assign()来实现

In [31]:
v = tf.Variable(5)
v.assign(v+1)
v

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=6>

##### Tensorflow还直接提供了assign_add(),assign_sub()方法来实现变量的加法和减法值的更新

In [32]:
v1 = tf.Variable(5)
v2 = tf.Variable(5)
v1.assign_add(1)
v2.assign_sub(1)
v1,v2

(<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=6>,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=4>)

###### 在Tensorflow中执行或开发Tensorflow代码,可以做
##### 导入Tensorflow时使用 import tensorflow.compat.v1 as tf 代替原来
##### 执行tf.disable_eager_execution()禁用Tensorflow2 默认的即时执行模式